### ISSUE TITLE
Do you plan to support MARINE?

### ISSUE THREAD

**Issue by n5-suzuki** [VOICEVOX/pyopenjtalk#15]
https://github.com/r9y9/pyopenjtalk#about-run_marine-option

Above project that you forked seems to have supported MARINE.
I love your project about using user_dictionary! I hope you to merge MARINE and user_dictionary.
Thank you.

**Comment by n5-suzuki** [comment]
ご返答ありがとうございます。

> baseとなっているpyopenjtalkのmainブランチをこちらにマージするつもりはあるか、ということでしょうか。
こちらおっしゃる通りでございます。

近々予定されていらっしゃれば待たせていただこうかと思っていましたが、未定という事で自分の方でも進みてみようと思います。とてもよく出来たらプルリクエストさせていただこうと思います！

**Comment by Hiroshiba** [comment]
ぜひお待ちしています！！
